DFE-Digital/SUI_Matcher

README.md

S UI 31 aspire spike docs update

---

Directory.Packages.props
README.md
app-host/Program.cs
auth-api/ApiMethods/Auth.cs
auth-api/Auth.csproj
auth-api/Lib/AuthClientCredentials.cs
auth-api/Lib/JwtHandler.cs
auth-api/Models/NhsDigitalKeyConstants.cs
auth-api/Program.cs
auth-api/Services/ITokenService.cs
auth-api/Services/StubTokenService.cs
auth-api/Services/TokenService.cs
external-api/ApiMethods/ExternalAuth.cs
external-api/Program.cs
external-api/Services/AuthServiceClient.cs
global.json
matching-api/ApiMethods/Match.cs
matching-api/Matching.csproj
matching-api/Program.cs
matching-api/Services/ExternalServiceClient.cs
shared/Shared/Helpers/RedisResourceHelper.cs
shared/Shared/Shared.csproj
sui-matching.sln
sui-tests/AuthEndpointIntegrationTests.cs
sui-tests/Lib/ApiFixture.cs
sui-tests/sui-tests.csproj
validate-api/Properties/launchSettings.json

SUI-39 Implemented the Auth Service integration with NHS Digital OAuth service

---

documentation/docs/architecture.md
documentation/docs/clientarchitecture.md

docs: Adding client arch docs

---

.github/workflows/gh-tag.yml

SUI-67
Creation of tags so we can deploy versioned code

bugfix: previous uses did not work as expected.

---

Directory.Packages.props
README.md
matching-api/Program.cs

sui-18
Fix the adding of the httpclient
Fix versions when trying to restore the project

bugfix: fixes after trying to run locally

---

app-host/infra/external-api.tmpl.yaml
app-host/infra/matching-api.tmpl.yaml
app-host/infra/yarp.tmpl.yaml
yarp/Yarp/Program.cs

SUI-67
Encountered a bug with yarp (https://github.com/microsoft/azure-container-apps/issues/1298). This has now been fixed. Have to specify environment which we now pass through.

feat: Get application working in azure

---

.github/workflows/gh-client-build.yml
SUI.Client.Watcher/infra/README.md
SUI.Client.Watcher/infra/client.bicep
app-host/infra/yarp.tmpl.yaml

sui-92
* Making sure the client being uploaded overwrites what is already there.
* Updating parameters of the client build due to limitations in running multiple processes (VM size)
* Updating yarp so that it is the external facing service and is available behind the private link
* Adding documentation for how to test in Azure. Includes powershell commands.

docs: Updating docs for how to run e2e tests in Azure

---

.github/workflows/gh-ci.yml
tests.runsettings

feat: Improving how code coverage is done

---

Directory.Packages.props
SUI.Azure.BlobStorage.Container.Sync/Program.cs
SUI.Azure.BlobStorage.Container.Sync/SUI.Azure.BlobStorage.Container.Sync.csproj
SUI.Client.Core/CsvFileProcessor.cs
SUI.Client.Core/CsvMappingConfig.cs
SUI.Client.Watcher/SUI.Client.Watcher.csproj
SUI.Client.Watcher/appsettings.e2etest.json
SUI.Client.Watcher/appsettings.json
SUI.Core/Constants.cs
SUI.Core/Endpoints/AuthToken/StubTokenService.cs
SUI.Core/Services/MatchingService.cs
SUI.E2E.Tests/Resources/Csv/single_match.csv
SUI.E2E.Tests/Resources/Csv/single_match_low_confidence.csv
SUI.E2E.Tests/Resources/Csv/single_match_really_low_confidence.csv
SUI.E2E.Tests/Resources/Csv/test_fail_validation.csv
SUI.Test/Integration/Adapters/MatchPersonServiceAdapter.cs
matching-api/CustomDateOnlyConverter.cs
sui-matching.sln

Added support for British date format
Added csv mapping support for gender and post code Bug fix with logging
Az blob storage container-FS sync tool

SUI-100 E2E test support 

---

app-host/infra/resources.bicep
app-host/infra/yarp.tmpl.yaml

corrected some additional bicep changes

SUI-98 Enabled encrypted peer-to-peer encryption in container apps env in bicep

---

app-host/infra/main.bicep
app-host/infra/monitoring.bicep

sui-112
Simple monitoring and alerting for the containers. Creates metric thresholds which will send an alert via email if breached.

feat: Adding monitoring and alerting to the service

---

documentation/docs/gettingstarted.md
documentation/docs/waysof.md

- Small update to help with onboarding, getting the NHS Developer setup
- Fix some minor typos

docs(readme): additional information on gettingstarted.md

---

SUI.Core/Domain/DemographicRequest.cs
SUI.Core/Endpoints/NhsFhirClient.cs
SUI.Core/Services/MatchingService.cs
SUI.Core/Services/ValidationService.cs
SUI.Test/Unit/MatchingServiceDemographicTests.cs
SUI.Test/Unit/MatchingServiceTests.cs
SUI.Types/DemographicResponse.cs
external-api/ExternalFhirEndpoint.cs
matching-api/MatchEndpoint.cs
matching-api/NhsFhirClientApiWrapper.cs
shared/Shared/Models/DemographicResult.cs
shared/Shared/Models/PatientDemographicResult.cs
sui-tests/sui-external-tests/ExternalApiIntegrationTests.cs
sui-tests/sui-external-tests/MockNhsFhirServer.cs
sui-tests/sui-external-tests/WireMockMappings/single_patient_demographic.json

A new endpoint to retrieve demographic data for a person by using their NHS Id.
- Added a new endpoint on MatchService to get demographic data by NHS id
- Added a new endpoint on External to get demographic data by NHD is
- Updated search service to include getting demographic data using NHS id
- Note: Was unusure whether to create a seperate service at this stage, but left it here for now.
- Added tests to support the demographic data retrieval.

Feature: 128 - demographic endpoint

---

SUI.Test/Unit/MatchingServiceTests.cs

sui-139:
Adding a test to ensure apostrophes work in the code base. This is handled by the FHIR client and all seems to work. I spent a long time test against a patient in the integration environment but it was due to mis formatting of the given name.
curl -H 'Content-Type: application/json' -d '{ "given":"WING MANN","family": "O'\''SIX-O'\''CLOCK", "birthdate": "2002-04-18"}' -X POST http://localhost:5000/matching/api/v1/matchperson
Tested against our service returns the number.

feat: Making sure apostrophes work

---

SUI.Client.Core/CsvFileProcessor.cs
SUI.E2E.Tests/E2EIntegrationTests.cs

Fixed an issue where running the SUI.Client.Console locally was thowing a DirectoryNotFound exception when using relative file paths. Absolute paths were fine.
Added a test to cover this scenario.

Bugfix: UI console directory bug

---

documentation/adrs/001-initial_approach.md

Corrected the formatting of the list of decisions, so that it formats correctly in Markdown when viewed on Github

Corrected formatting in ADR 001

---

SUI.Core/Services/MatchingService.cs
SUI.Test/Unit/MatchingServiceTests.cs

- Added a new log information with details specified in Jira ticket
- Added a unit test to prove it's logging.
Unsure of the aggregate string helper, so any suggestions are welcome too

Feat: 143 - match demographic logging

---

SUI.Azure.BlobStorage.Container.Sync/Program.cs
SUI.Core/Domain/ValidationResponse.cs
SUI.Core/Endpoints/AuthToken/TokenService.cs
SUI.Core/Services/MatchingService.cs
SUI.E2E.Tests/SUI.E2E.Tests.csproj
SUI.E2E.Tests/Util/AppHostFixture.cs
SUI.Test.FakeNhsFhirApi/FakeItem.cs
SUI.Test.FakeNhsFhirApi/FakePerson.cs
SUI.Test.FakeNhsFhirApi/Generator.cs
SUI.Test.FakeNhsFhirApi/Program.cs
SUI.Test/Integration/CsvProcessorTests.cs
SUI.Test/Integration/TestContextLoggerProvider.cs
SUI.Test/Integration/TxtProcessorTests.cs
SUI.Test/Unit/MatchingServiceTests.cs
SUI.Test/Unit/ValidateServiceTest.cs
app-host/HealthCheckExtensions.cs
matching-api/Matching.csproj
matching-api/NhsFhirClientApiWrapper.cs
sui-tests/app-host-tests/AppHost.IntegrationTests.csproj
sui-tests/app-host-tests/AppHostFixture.cs

Removed all build warnings.
Updated some syntax
There were some AppHost SDK inclusions in non AppHost applications as well which were causing warnings.

Chore: 175 - resolve build warnings

---

documentation/adrs/002-client_distribution.md
documentation/docs/adrs.md

Create a draft ADR for distribution of the CLI client tools

docs(ADR): ADR 002

---

.github/workflows/gh-deploy-infra.yml
app-host/infra/deploy_readme.md
app-host/infra/main.bicep
app-host/infra/main.parameters.json
app-host/infra/monitoring.bicep
app-host/infra/resources.bicep
app-host/infra/secrets/secrets.module.bicep

- Moved DfE specific variable values to params in the bicep files
- Updated github CI so pass our variables in that were originally in the bicep files
- Added a what-if. This is 1 step short of a approval gate but want to see if this works for now
When checking this PR. Please be thorough in ensuring I have caught all DfE specific vars. I am ensure about logging/resource specific names that come after the prefix and environment name (e.g. `{prefix}-{environmentname}-01`)

Feat: 132 - infra parametarize

---

.github/workflows/gh-deploy-app.yml
.github/workflows/gh-deploy-infra.yml

Fix an issue with the pipeline

fix: issue with app deploy missing vars

---

.github/workflows/gh-deploy-app.yml
.github/workflows/gh-deploy-infra.yml
app-host/infra/main.bicep
app-host/infra/main.parameters.json
app-host/infra/resources.bicep

- Updated various files to align the parameters.
- what-if command now working.
The What-if is working as far as I can tell. Unsure about deployment at this stage

Feat: 132 - infra build

---

.github/workflows/gh-smoke-test.yml

removed the quotes from the cron_run='true', so the scheduler can work properly

SUI-153 Fixed the cron job flag.

---

SUI.Core/Domain/PersonSpecification.cs
SUI.Core/Util/GenderToLowercaseConverter.cs

Only lowercase genders allowed
```
[AllowedValues("male", "female", "unknown", "other")]
public string? Gender ...
```

SUI-41 Updated the SUI Client to convert Gender provided in the CSVs to lowercase

---

SUI.Core/Services/MatchingService.cs
SUI.Test/Unit/MatchingServiceTests.cs

sui-88
Change of plan for the ticket... Instead of doing the mapping ourselves, we are going to try mapping it within powerBI. In order to do this we just need the outer code for a postcode so this PR is to achieve that for the logs.

feat: reducing the output to the outercode for postcode.

---

SUI.Core/Services/MatchingService.cs
SUI.Test/Unit/MatchingServiceTests.cs

This reverts commit 831d96c2c02e4e9498ef7d8d851574935c77ebb9.

Revert "feat: reducing the output to the outercode for postcode."

---

.github/workflows/gh-deploy-app.yml
.github/workflows/gh-deploy-infra.yml
SUI.Test/Integration/TxtProcessorTests.cs
src/Shared/Logging/JsonFileLoggerProvider.cs
src/tools/dbs-response-logger/SUI.DBS.Client.Core/TextFileProcessor.cs

SUI-109
Added new log message to DBS Client
> [Information] [SearchId=41317b5e89b90dae894b328a4085f962] [MATCH_COMPLETED] MatchStatus: NoMatch, AgeGroup: 4-7 years, Gender: Male, Postcode: WN1 1YN

SUI-109 Added demographic logging for DBS response

---

src/app-host/infra/resources.bicep

- Add delegation to allow managedEnv to create a subnet (See build error)
- Add a bigger IP space on the VNET
- Formatting update in resource.bicep

chore: vnet and delegation

---

.github/workflows/gh-client-infra-deploy.yml
.github/workflows/gh-deploy-app.yml

Update incorrect file path for client

chore: update client template file

---

.github/workflows/gh-deploy-app.yml

see if we can list .env vars from bicep

chore: list env

---

.github/workflows/gh-client-infra-deploy.yml
src/tools/client/SUI.Client.Watcher/infra/client.bicep

client infra build failing on missing params. I've added them via secrets as recommended

CI: add missing params

---

.github/workflows/gh-client-infra-deploy.yml
src/tools/client/SUI.Client.Watcher/infra/client.bicep

It can be added manually if needed.

chore: remove VM diagnostics

---

.github/workflows/gh-client-infra-deploy.yml

fix a formatting error in the client infra workflow what-if

CI: formatting error

---

src/tools/client/SUI.Client.Watcher/infra/client.bicep

Removed peering. Updating VNET/Subnet range on vnetfw.

feat: update client.bicep

---

.github/workflows/gh-publish-nuget.yml
src/tools/client/SUI.Client.Watcher/README.md
src/tools/client/SUI.Client.Watcher/SUI.Client.Watcher.csproj
src/tools/dbs-response-logger/SUI.DBS.Response.Logger.Watcher/README.md
src/tools/dbs-response-logger/SUI.DBS.Response.Logger.Watcher/SUI.DBS.Response.Logger.Watcher.csproj

- Updated README's
- Added a manual trigger workflow for now

Feat: 71 - nuget package setup

---

src/tools/client/SUI.Client.Watcher/infra/README.md
src/tools/client/SUI.Client.Watcher/infra/README_Deployment.md
src/tools/client/SUI.Client.Watcher/infra/client.bicep

- Updated the readme to reflect new changes to client deployment
- Updated the firewall policy that reflects the working changes made in azure

chore: Update readme and client firewall

---

Directory.Packages.props
test_and_cover.ps1
tests.runsettings
tests/Unit.Tests/Client/CsvProcessorTests.cs
tests/Unit.Tests/Client/FieldComparerServiceTests.cs
tests/Unit.Tests/DbsResponseLogger/TxtProcessorTests.cs
tests/Unit.Tests/External/NhsFhirClientTests/BaseNhsFhirClientTests.cs
tests/Unit.Tests/External/NhsFhirClientTests/PerformSearchByNhsIdTests.cs
tests/Unit.Tests/External/NhsFhirClientTests/PerformSearchTests.cs
tests/Unit.Tests/GlobalUsings.cs
tests/Unit.Tests/Logging/ApplicationEnricherTests.cs
tests/Unit.Tests/MSTestSettings.cs
tests/Unit.Tests/Matching/CustomDateOnlyConverterTests.cs
tests/Unit.Tests/Matching/MatchingServiceDemographicTests.cs
tests/Unit.Tests/Matching/MatchingServiceTests.cs
tests/Unit.Tests/Matching/ValidateServiceTest.cs
tests/Unit.Tests/Unit.Tests.csproj
tests/Unit.Tests/Util/TestContextLoggerProvider.cs

Moved Unit.Tests from MSSTest to XUnit. Now all the projects are using the same test library

Tests: 45 - ms test to xunit

---

src/app-host/HealthCheckExtensions.cs
test_and_cover.ps1
tests/Unit.Tests/External/JwtHandlerTests.cs
tests/Unit.Tests/Util/JwtPemHelper.cs

A few more tests to get more coverage.
I have intentionally left the TokenService and AuthClientCredentials for now as I think they could be refactored to be more testable.

Tests: 45 - Unit tests

---

src/Shared/Endpoint/IMatchingService.cs
src/Shared/Models/DataQualityResult.cs
src/external-api/Services/NhsFhirClient.cs
src/external-api/Services/SearchParamsFactory.cs
src/matching-api/NhsFhirClientApiWrapper.cs
src/matching-api/Services/DataQualityEvaluatorService.cs
src/matching-api/Services/MatchingService.cs
src/tools/client/SUI.Client.Core/CsvFileProcessor.cs
src/tools/client/SUI.Client.Watcher/Program.cs
src/tools/dbs-response-logger/SUI.DBS.Response.Logger.Core/TextFileProcessor.cs
src/tools/dbs-response-logger/SUI.DBS.Response.Logger.Watcher/Program.cs
tests/Integration.Tests/AppHost/AppHostIntegrationTests.cs
tests/Unit.Tests/External/NhsFhirClientTests/PerformSearchTests.cs
tests/Unit.Tests/External/Services/SearchParamsFactoryTests.cs
tests/Unit.Tests/Matching/DataQualityEvaluatorServiceTests.cs
tests/Unit.Tests/Matching/MatchingServiceTests.cs

Updates to address the 'Blocker' and 'High' issues found in sonarcloud issues

chore: - 399 - sonarcloud issues pt1

---

.github/workflows/gh-ci.yml

Add on push to main to anayse the main branch for sonarcloud

CI: add main branch analysis

---

src/app-host/SwaggerUi/SwaggerUiExtensions.cs
src/tools/client/SUI.Client.Console/Program.cs
src/tools/client/SUI.Client.Core/CsvFileProcessor.cs
src/tools/client/SUI.Client.Core/PdfReportGenerator.cs
src/tools/client/SUI.Client.Core/Watcher/CsvFileMonitor.cs
src/tools/client/SUI.Client.Core/Watcher/CsvFileWatcherService.cs
src/tools/client/SUI.Client.Core/Watcher/FileProcessedResult.cs
src/tools/client/SUI.Client.Watcher/Program.cs
src/tools/client/SUI.Client.Watcher/infra/client.bicep
src/tools/dbs-response-logger/SUI.DBS.Response.Logger.Console/Program.cs
src/tools/dbs-response-logger/SUI.DBS.Response.Logger.Core/TextFileProcessor.cs
src/tools/dbs-response-logger/SUI.DBS.Response.Logger.Watcher/Program.cs
tests/E2E.Tests/Client/E2EIntegrationTests.cs

Feat: 399 - sonarcloud pt4

---

.github/workflows/gh-client-infra-deploy.yml

Making the infra deployment pipeline run whenever there has been a change to the infra directory.

improvement: no-ref

---

.github/workflows/gh-client-infra-deploy.yml
.github/workflows/gh-deploy-infra.yml

Moving the steps to auto deploy from client to application action.

Bugfix/no ref/wrong file

---

src/tools/client/SUI.Client.Watcher/infra/client.bicep

Add a property as it needs properties. 
Value comes from Azure

CI: add back in properties

---

src/tools/client/SUI.Client.Core/CsvFileProcessor.cs
src/tools/client/SUI.Client.Core/Watcher/CsvFileMonitor.cs
src/tools/client/SUI.Client.Core/Watcher/CsvFileWatcherService.cs
tests/E2E.Tests/Client/E2EIntegrationTests.cs

Adding log messages to the file processor so we can tell that it is actually processing the records.

Improvement: Add logging to the file processor

---

src/matching-api/Services/MatchingService.cs
tests/Unit.Tests/Matching/CustomDateOnlyConverterTests.cs

noticed a few very minor issues to resolve.
- Uncreachable code because there is always a query built before it.
- Tests can re use a serializer

feat: 399 - minor issues

---

src/tools/client/SUI.Client.Core/CsvFileProcessor.cs

Updated logging so we can see progress of processing. 
Currently we add a log for every record but it wasn't providing any value and causing large log files. Update means we can log less but can still see it is processing.

chore: logging improvements

---

src/app-host/infra/resources.bicep

Removing blob storage as we don't use it anymore

refactor: remove storage

---

.github/actions/env-setup/action.yml
.github/workflows/gh-smoke-test-nightly.yml
.github/workflows/gh-smoke-test.yml

split out the day and night jobs. Some duplications but reduces complexity a bit. 
Not married to this but might be a solution for now.
Night job is purely on CRON and has a dependency on jobs so they don't run in parallel

ci : 457 - smoke tests

---

.github/workflows/gh-smoke-test-nightly.yml

checkout on nightly run

---

.github/workflows/gh-ci.yml

add write permission as per docs
https://github.com/marocchino/sticky-pull-request-comment

CI: add write permission

---

.github/workflows/gh-smoke-test-executer.yml

- Changed success message for client as the old one logged even if something went wrong.
- Added a error message check as well so it can fail early

tests: improve success/fail check

---

.github/workflows/gh-smoke-test-executer.yml

Always keep smoke logs to inspect

tests: smoke logs

---

src/tools/client/SUI.Client.Core/Extensions/ServiceCollectionExtensions.cs
src/tools/client/SUI.Client.Watcher/Program.cs
tests/Unit.Tests/Client/CsvProcessorTests.cs

Moved it out of AddClientCore and used recommended AddHttpClient

chore: http client on watcher

---

.gitignore
Directory.Packages.props
src/Shared/Extensions/HostBuilderExtensions.cs
src/external-api/External.csproj
src/external-api/ExternalFhirEndpoint.cs
src/external-api/Program.cs
src/external-api/appsettings.json
src/matching-api/DownstreamApiAuthHandler.cs
src/matching-api/MatchEndpoint.cs
src/matching-api/Matching.csproj
src/matching-api/Program.cs
src/matching-api/appsettings.json
src/tools/client/SUI.Client.Core/Integration/MatchPersonApiService.cs
src/tools/client/SUI.Client.Watcher/Program.cs
src/tools/client/SUI.Client.Watcher/SUI.Client.Watcher.csproj
src/tools/client/SUI.Client.Watcher/appsettings.json
tests/E2E.Tests/Client/AppHostFixture.cs
tests/E2E.Tests/Client/E2EIntegrationTests.cs
tests/Integration.Tests/AppHost/AppHostFixture.cs
tests/Integration.Tests/AppHost/AppHostIntegrationTests.cs
tests/Integration.Tests/External/ExternalApiFixture.cs
tests/Integration.Tests/External/ExternalApiIntegrationTests.cs
tests/Unit.Tests/Client/MatchPersonApiServiceTests.cs
tests/Unit.Tests/Matching/DownstreamApiAuthHandlerTests.cs

added auth to the client and both apis.
updated the tests to also connect with auth if it is turned on.
values can be set in .env file.

added authentication with Entra ID

---

.github/workflows/gh-deploy-app.yml
.github/workflows/gh-deploy-infra.yml
Directory.Packages.props
documentation/adrs/003-audit-logging.md
src/Shared/Constants.cs
src/Shared/Logging/AuditLogger.cs
src/Shared/Logging/ChannelAuditLogger.cs
src/Shared/Shared.csproj
src/app-host/AppHost.csproj
src/app-host/Program.cs
src/app-host/Properties/launchSettings.json
src/app-host/appsettings.Development.json
src/app-host/appsettings.json
src/app-host/infra/audit_deploy_readme.md
src/app-host/infra/main.bicep
src/app-host/infra/main.parameters.json
src/app-host/infra/matching-api.tmpl.yaml
src/app-host/infra/resources.bicep
src/matching-api/AuditLogBackgroundService.cs
src/matching-api/Matching.csproj
src/matching-api/Program.cs
src/matching-api/Services/MatchingService.cs
tests/Unit.Tests/Client/CsvProcessorTests.cs
tests/Unit.Tests/Matching/AuditLogBackgroundServiceTests.cs
tests/Unit.Tests/Matching/MatchingServiceDemographicTests.cs
tests/Unit.Tests/Matching/MatchingServiceTests.cs

This is a proof of concept to add a AuditLogger to the application. This is by no means a final version and will be updated as we gather more requirements.
Technologies added:
- Azure storage tables
- Feature flag management service
This feature is behind a feature flag in both Infrastructure and Application code so that we can merge into main without effecting existing workflow. Mosty so we don't have a long life branch that could go stale and/or be difficult to rebase.
To test locally:
- Change the launch settings feature flag to 'true' and then run the app. It should work first time. It will create a azurite docker image for storage. Then you can run the matching API and see if logs appear in the Audit table.
TODO:

Poc - SUI-565 - audit logger

---

src/matching-api/Services/MatchingService.cs
tests/Unit.Tests/Matching/MatchingServiceTests.cs

Added some additional queries with less parameters because according to the NHS PDS documentation, A valid Given, Family and Dob, with an invalid Gender, PostCode or else. has less of a confidence score than the Given, Family and Dob alone.

SUI-630 Added some more queries with less parameters

---

.github/workflows/gh-smoke-test-executer.yml
Directory.Packages.props
src/tools/client/SUI.Client.Core/CsvFileProcessor.cs
src/tools/client/SUI.Client.Core/Watcher/CsvWatcherConfig.cs
src/tools/client/SUI.Client.Watcher/Program.cs
src/tools/client/SUI.Client.Watcher/Properties/launchSettings.json
src/tools/client/SUI.Client.Watcher/README.md
src/tools/client/SUI.Client.Watcher/SUI.Client.Watcher.csproj
src/tools/client/SUI.Client.Watcher/WatcherArgs.cs
src/tools/client/SUI.Client.Watcher/infra/README.md
tests/E2E.Tests/Client/E2EIntegrationTests.cs
tests/Unit.Tests/Client/CsvProcessorTests.cs

Adds a flag from program args for using gender in search
!!Breaking change!!
This next version uses cli option args to get values. This is more robust and scalable as it has built in validation, built in documentation and we do not need to worry about the order of arguments. Generally less code to maintain.

feat: SUI-622 - gender flag option

---

src/Shared/Models/MatchResult.cs
src/Shared/Models/MatchResult2.cs
src/matching-api/Services/MatchingService.cs
tests/Integration.Tests/AppHost/AppHostFixture.cs
tests/Integration.Tests/AppHost/AppHostIntegrationTests.cs
tests/Integration.Tests/AppHost/MockNhsFhirServer.cs
tests/Unit.Tests/Matching/MatchingServiceTests.cs

- Now performs several of the queries, we stop on the desired result (status: Match, confidence score: 1), otherwise we carry on and return the best of the bunch.
- To improve the readability of the process stages in the logs, query codes were added instead of the index numbers.

SUI-630 Updated the algorithm to return the best query result

---

src/Shared/Logging/JsonFileLoggerProvider.cs
src/matching-api/Services/MatchingService.cs
src/tools/dbs-response-logger/SUI.DBS.Response.Logger.Core/TextFileProcessor.cs
tests/Unit.Tests/DbsResponseLogger/TxtProcessorTests.cs
tests/Unit.Tests/Util/JsonTestContextLoggerProvider.cs
tests/Unit.Tests/Util/TempDirectoryFixture.cs
tests/Unit.Tests/Util/TestContextLoggerProvider.cs

- Now the DBS and SUI SearchIds match
- Now if the search algorithm results in ManyMatch the latest queryCode is returned

SUI-625 Used the last modified date of the input file to separate to the log files and timestamps for each log message

---

src/tools/client/SUI.Client.Core/CsvFileProcessor.cs
src/tools/client/SUI.Client.Core/Watcher/CsvWatcherConfig.cs
src/tools/client/SUI.Client.Core/Watcher/WatcherArgs.cs
src/tools/client/SUI.Client.Watcher/Program.cs
tests/Unit.Tests/Client/CsvProcessorTests.cs
tests/Unit.Tests/Client/ProcessCsVFileAsyncTests.cs

- New code and args to output only matched records to a specified directory.
- Tests to support
Note: I've kept the IO in the processor file for now but in a single method which will be simple to refactor if need be.

feat: 706 - match output

---

documentation/docs/architecture.md
src/Shared/Models/SearchSpecification.cs
src/matching-api/Search/SearchStrategy3.cs
src/tools/client/SUI.Client.Core/MatchingCsvFileProcessor.cs
src/tools/client/SUI.Client.Core/Models/MatchPersonPayload.cs
src/tools/client/SUI.Client.Core/Watcher/CsvWatcherConfig.cs
src/tools/client/SUI.Client.Core/Watcher/WatcherArgs.cs
src/tools/client/SUI.Client.Watcher/Program.cs
src/tools/client/SUI.Client.Watcher/Properties/launchSettings.json
tests/Unit.Tests/DbsResponseLogger/TxtProcessorTests.cs
tests/Unit.Tests/Models/SearchSpecificationTests.cs

client can now pass the strategy through
Updated the API strat 3 as well to start simply, then we will iterativly update it

feat: pass through strategy

---

src/matching-api/Search/ISearchStrategy.cs
src/matching-api/Search/SearchQueryBuilder.cs
src/matching-api/Search/SearchStrategy1.cs
src/matching-api/Search/SearchStrategy2.cs
src/matching-api/Search/SearchStrategy3.cs
tests/Unit.Tests/DbsResponseLogger/TxtProcessorTests.cs
tests/Unit.Tests/Matching/SearchStrategyTests.cs

Strategy3 has been updated to include many iterative versions.
I've added a comment and set it to version 14 which based on testing has been the most optimal.
A future piece of work will be to pass through a version on the client and API so that any version can be selected.

feat: 722 - algorithm updates
